global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'prometheus'

  target_groups:
    - targets: ['localhost:9090']

- job_name: 'kubernetes-cluster'

  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  scheme: https

  kubernetes_sd_configs:
  - masters:
    - 'https://kubernetes.default.svc'
    in_cluster: true
    kubelet_port: 10250

  relabel_configs:
  - source_labels: [__meta_kubernetes_role]
    action: keep
    regex: ^(?:master|node)$
  - action: labelmap
    regex: ^__meta_kubernetes_node_label_(.+)$
    replacement: $1
  - source_labels: [__meta_kubernetes_role]
    action: replace
    regex: ^(.+)$
    target_label: kubernetes_role
    replacement: $1

- job_name: 'kubernetes-services'

  kubernetes_sd_configs:
  - masters:
    - 'https://kubernetes.default.svc'
    in_cluster: true

  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: ^true$
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    action: replace
    target_label: __scheme__
    regex: ^(https?)$
    replacement: $1
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: ^(.+)$
    replacement: $1
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: ^(.+)(?::\d+);(\d+)$
    replacement: $1:$2
  - action: labelmap
    regex: ^__meta_kubernetes_service_label_(.+)$
    replacement: $1
  - source_labels: [__meta_kubernetes_role]
    action: replace
    regex: ^(.+)$
    target_label: kubernetes_role
    replacement: $1
  - source_labels: [__meta_kubernetes_service_namespace]
    action: replace
    regex: ^(.+)$
    target_label: kubernetes_namespace
    replacement: $1
  - source_labels: [__meta_kubernetes_service_name]
    action: replace
    regex: ^(.+)$
    target_label: kubernetes_name
    replacement: $1
