---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
  name: "gerrit"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "gerrit"
    provider: "fabric8"
  type: "LoadBalancer"
