spec:
  replicas: 1
  template:
    spec:
      serviceAccount: metrics
      containers:
      - name: prometheus
        image: prom/prometheus:0.20.0
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data-volume
          mountPath: /prometheus
        livenessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: data-volume
        emptyDir: {}
