spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: metrics
      containers:
      - name: prometheus
        image: prom/prometheus:v1.0.1
        args:
          - -config.file=/etc/prometheus/config/prometheus.yml
          - -storage.local.path=/prometheus
          - -web.console.libraries=/etc/prometheus/console_libraries
          - -web.console.templates=/etc/prometheus/consoles
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/config
        - name: data-volume
          mountPath: /prometheus
        livenessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: data-volume
        emptyDir: {}
