metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    provider: "fabric8"
    expose: "true"
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090
