spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: grafana
        livenessProbe:
          httpGet:
            port: 3000
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            port: 3000
          initialDelaySeconds: 5
