---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "gogs"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      volumes:
      - name: gogs-data
        persistentVolumeClaim:
          claimName: gogs-data
      - name: gogs-repositories
        persistentVolumeClaim:
          claimName: gogs-repositories
      containers:
      - env:
        - name: "DOMAIN"
          valueFrom:
            configMapKeyRef:
              key: "domain"
              name: "gogs"
        - name: "GOGS_SERVER__ROOT_URL"
          valueFrom:
            configMapKeyRef:
              key: "gogs-server--root-url"
              name: "gogs"
        - name: "ADMIN_USER_EMAIL"
          valueFrom:
            configMapKeyRef:
              key: "admin-user-email"
              name: "gogs"
        - name: "ADMIN_USER_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "admin-user-password"
              name: "gogs"
        - name: "GOGS_SERVER__PROTOCOL"
          valueFrom:
            configMapKeyRef:
              key: "gogs-server--protocol"
              name: "gogs"
        - name: "GOGS_OAUTH_OPENSHIFT__ENABLED"
          value: "true"
        - name: "ADMIN_USER_CREATE"
          value: "true"
        - name: "GOGS_OAUTH_OPENSHIFT__TOKEN_URL"
          valueFrom:
            configMapKeyRef:
              key: "gogs-oauth-openshift--token-url"
              name: "gogs"
        - name: "GOGS_OAUTH_OPENSHIFT__SCOPES"
          valueFrom:
            configMapKeyRef:
              key: "gogs-oauth-openshift--scopes"
              name: "gogs"
        - name: "GOGS_OAUTH_OPENSHIFT__AUTH_URL"
          valueFrom:
            configMapKeyRef:
              key: "gogs-oauth-openshift--auth-url"
              name: "gogs"
        - name: "GOGS_WEBHOOK__TASK_INTERVAL"
          value: "true"
        - name: "GOGS_WEBHOOK__SKIP_TLS_VERIFY"
          value: "true"
        - name: "GOGS_SERVER__DOMAIN"
          valueFrom:
            configMapKeyRef:
              key: "gogs-server--domain"
              name: "gogs"
        - name: "ADMIN_USER_NAME"
          valueFrom:
            configMapKeyRef:
              key: "admin-user-name"
              name: "gogs"
        - name: "GOGS_OAUTH_TWITTER__ENABLED"
          value: "false"
        - name: "GOGS_OAUTH__ENABLED"
          value: "true"
        - name: "KUBERNETES_ADMIN_USER"
          valueFrom:
            configMapKeyRef:
              key: "kubernetes-admin-user"
              name: "gogs"
        - name: "GOGS_OAUTH_OPENSHIFT__CLIENT_ID"
          value: "gogs"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/gogs:${project.version}"
        imagePullPolicy: "IfNotPresent"
        name: "gogs"
        ports:
        - containerPort: 22
          name: "ssh"
        - containerPort: 3000
          name: "http"
        volumeMounts:
        - mountPath: /opt/gogs/data
          name: gogs-data
        - mountPath: /home/git
          name: gogs-repositories
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      serviceAccountName: "gogs"
