apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: gogs-da
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi