spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: exposecontroller
        image: fabric8/exposecontroller:${project.version}
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        args:
          - --v=8
        volumeMounts:
        - name: config-volume
          mountPath: /etc/exposecontroller
      volumes:
      - name: config-volume
        configMap:
          name: exposecontroller
      serviceAccountName: exposecontroller
