---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hubot"
  labels:
    provider: "fabric8"
    expose: "true"
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: "hubot-slack"
