spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: jboss/keycloak:2.2.0.Final
        env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
      volumeMounts:
      - mountPath: /opt/jboss/keycloak/standalone/data
        name: keycloak-data
        readOnly: false
      - mountPath: /opt/jboss/keycloak/standalone/configuration
        name: keycloak-config
        readOnly: false
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data
      - name: keycloak-config
        persistentVolumeClaim:
          claimName: keycloak-config
