---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    name: "letschat"
    provider: "fabric8"
  name: "letschat"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "letschat"
  template:
    metadata:
      labels:
        name: "letschat"
        provider: "fabric8"
      name: "letschat"
    spec:
      containers:
      - image: "mongo"
        name: "letschat-mongodb"
        ports:
        - containerPort: 27017
          protocol: "TCP"
      - env:
        - name: "LETSCHAT_CREATE_HUBOT_USER"
          value: "true"
        - name: "LETSCHAT_HUBOT_TOKEN"
          value: "${LETSCHAT_HUBOT_TOKEN}"
        - name: "LETSCHAT_HUBOT_PASSWORD"
          value: "${HUBOT_PASSWORD}"
        - name: "LETSCHAT_HUBOT_USERNAME"
          value: "${HUBOT_USERNAME}"
        - name: "LETSCHAT_HUBOT_EMAIL"
          value: "fabric8-admin@googlegroups.com"
        - name: "LETSCHAT_HUBOT_FIRST_NAME"
          value: "fabric8"
        - name: "LETSCHAT_HUBOT_LAST_NAME"
          value: "rocks"
        - name: "LETSCHAT_HUBOT_DISPLAY_NAME"
          value: "fabric8"
        - name: "LETSCHAT_DEFAULT_ROOMS"
          valueFrom:
            configMapKeyRef:
              key: "letschat-default-rooms"
              name: "letschat"
        - name: "LCB_NOROBOTS"
          value: "false"
        - name: "LCB_FILES_ENABLE"
          value: "true"
        - name: "LCB_DATABASE_URI"
          value: "mongodb://127.0.0.1:27017/letschat"
        image: "fabric8/lets-chat:${project.version}"
        name: "letschat"
        ports:
        - containerPort: 5000
          protocol: "TCP"
