metadata:
  namespace: fabric8-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx-ingress
        image: nginxdemos/nginx-ingress:0.3
        args:
          - -v=3
          - -nginx-configmaps=fabric8-system/nginx-config
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
      nodeSelector:
          externalIP: true
