---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    fabric8.io/type: "preview"
  name: "jenkins"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: "fabric8/jenkins-openshift:dev"
        imagePullPolicy: "Always"
        name: "jenkins"
        ports:
        - containerPort: 50000
          name: "slave"
        - containerPort: 8080
          name: "http"
        env:
        - name: JENKINS_PASSWORD
          value: admin
        volumeMounts:
        - mountPath: /var/lib/jenkins/jobs
          name: jenkins-jobs
          readOnly: false
        - mountPath: /var/lib/jenkins/workspace
          name: jenkins-workspace
          readOnly: false
      serviceAccountName: "jenkins"
      volumes:
      - name: jenkins-jobs
        persistentVolumeClaim:
          claimName: jenkins-jobs
      - name: jenkins-workspace
        persistentVolumeClaim:
          claimName: jenkins-workspace