apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${project.artifactId}-jobs"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: "${project.artifactId}-jobs"
